# example-app-chart/values.yaml
replicaCount: 3
service:
  type: ClusterIP
  port: 80
  targetPort: 80
container:
  # Porta que o container está escutando (padrão NGINX)
  port: 80
image:
  repository: lucasrios92/teste-kotlin
  tag: sha-6bbec76
